[package]
name = "chewy_coin"
version = "1.0.0"
authors = []

[addresses]
coin_address = "0xc26a8eda1c3ab69a157815183ddda88c89d6758ee491dd1647a70af2907ce074"

#[dev-addresses]
#coin_address = "0xc26a8eda1c3ab69a157815183ddda88c89d6758ee491dd1647a70af2907ce074"

[dependencies.AptosFramework]
git = "https://github.com/aptos-labs/aptos-core.git"
rev = "mainnet"
subdir = "aptos-move/framework/aptos-framework"

[dependencies.AptosTokenObjects]
git = 'https://github.com/aptos-labs/aptos-core.git'
rev = 'mainnet'
subdir = 'aptos-move/framework/aptos-token-objects'
